### ISSUE TITLE
Compatibility table typo

### ISSUE THREAD

**Issue by mrfixpl** [Mr-MIBonk/M.I.B._More-Incredible-Bash#10]
Hi! Just a minor thing but still I'm gonna report it.
Instead of `MHI2Q_ER_AUG22_P4212_MU1117` it should be `MHI2Q_ER_AUG22_P4212_MU1177`.

![Zrzut ekranu 2022-05-24 o 12 33 48](https://user-images.githubusercontent.com/103274854/170012188-ff4ae3f1-ea47-4716-9247-69b77245f185.png)

**Comment by harman-f** [comment]
Fixed
