### ISSUE TITLE
About patch for MHI2Q_CN_AUG22_P1404

### ISSUE THREAD

**Issue by johnzhouinfo** [Mr-MIBonk/M.I.B._More-Incredible-Bash#115]
Hi,
The MIB is working fine on this version, but I wonder if there be a patch for this version soon? 
ps: I already uploaded a backup to mibsolution.one in case you wish to look at it

**Comment by harman-f** [comment]
You cane rename patch folder `MHI2Q_CN_AUG22_P1002_MU1002_PATCH` to `MHI2Q_CN_AUG22_P1404_MU1404_PATCH`

ifs-root-stage2 is the same between both versions

**Comment by johnzhouinfo** [comment]
The patch was installed successfully. 
Thanks a lot!

**Comment by tushenyu** [comment]
MHI2Q_CN_AUG22_P1404  Where can I download it?
