### ISSUE TITLE
Large files near impossible to download.

### ISSUE THREAD

**Issue by DaveArthur** [Mr-MIBonk/M.I.B._More-Incredible-Bash#13]
Copy direct link is not working so stuck with default browser download manager. 

Would it not be possible to store as torrents?

**Comment by harman-f** [comment]
Which one do you exactly mean?

**Comment by DaveArthur** [comment]
https://mibsolution.one/#/1/15/MST2

**Comment by harman-f** [comment]
Might be rioght, but not at all related to M.I.B or even MHI2 units.

You might want to have a look here: https://mibwiki.one/doc/mibsolutionone-fix-download-speed-sxBSYsX5Qq
