### ISSUE TITLE
Cant flash

### ISSUE THREAD

**Issue by benassyGT** [Mr-MIBonk/M.I.B._More-Incredible-Bash#133]
Hi in one unit cant flash..

![IMG-20230226-WA0035](https://user-images.githubusercontent.com/123642574/221609018-7299801d-ef2d-444f-b097-e3a3138f7ddc.jpg)

![IMG-20230227-WA0000](https://user-images.githubusercontent.com/123642574/221609254-985decea-93ea-4932-afdd-9b4d9acb2be7.jpg)

And yes, patch folder is not empty :D

**Comment by harman-f** [comment]
In that case your unit is already patched as stated on screen ;)
![image](https://user-images.githubusercontent.com/98130152/221677903-e6bd84ba-fd36-4668-a34f-09b5196eab04.png)

**Comment by benassyGT** [comment]
But no FEC... Only one and it is maps

Dne po 27. 2. 2023 21:27 uživatel harman-f ***@***.***>
napsal:

**Comment by harman-f** [comment]
your log file would be helpful.

Try to run addFec again.

**Comment by Silintone** [comment]
Maybe i can help

To add the fec license for maps , download the patch if required , here is a link , ive uploaded all the patches for all the units as its a long slow download.

https://drive.google.com/drive/folders/1SLgE_u-ADXoPpxV2MuzQHFpUHoBCVcFT?usp=share_link

Look for yours and copy to patch file on sd card.
in the patch files look for the tect file , edit it and add the correct code.

EU  fec code is   023000ee
ROW fec code is 023d0030

This resolved my issue like this.
