### ISSUE TITLE
Add EQ controls for MHI2 Skoda

### ISSUE THREAD

**Issue by HeinanCA** [Mr-MIBonk/M.I.B._More-Incredible-Bash#134]
Hey,
I have Skoda Karoq with MIB 2.5 Retrofitted (Canton is original), SW version 1440.

I currently have 3 EQ fields, and I wonder if it is possible to increase this to 5 EQ sliders?
Meaning, also have Mid-Bass, Mid-Treble. Even with Canton, sound is not satisfying (moved from BOSE system on Audi A6 Avant which was far better).

Thank you!

**Comment by harman-f** [comment]
Yes, it is possible, but the display is bugg in many GUIs on Skoda.

Get Notepad++
And open the subwoofer file from /apps/ on SD card

Change the marked `03` to `05`
![image](https://user-images.githubusercontent.com/98130152/221678579-fce10374-e22a-452a-8cff-42be72a33903.png)

And run the patch again in GEM.

Report back here with screenshots!

**Comment by HeinanCA** [comment]
@harman-f  point is - I can't run the patch, because I have Canton, so it stops running (says "We will stop here, this is only for Internal sound system on 5F".

Anyway I can activate only the EQ sliders, with Canton?

**Comment by harman-f** [comment]
That is a very good question.
No idea if it is enought to just change that setting to get the 2 additional working EQs.

Do you have VCP?
Doing it the manual way for testing would be quickist.
If you can confirm this to be working I could built soemthing around it.

**Comment by HeinanCA** [comment]
No, only VCDS (unfortunately)

**Comment by harman-f** [comment]
[subwoofer.txt](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/10870787/subwoofer.txt)

This is a dirty hack...
renaname the file back to `subwoofer` and replace in /apps/
run command in GEM again.

Report back.

**Comment by HeinanCA** [comment]
> [subwoofer.txt](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/10870787/subwoofer.txt)
> 
> This is a dirty hack... rename the file back to `subwoofer` and replace the version in /apps/ run command in GEM again.
> 
> Report back.

Didn't work. Still 3 EQ only, not 5 😞

**Comment by harman-f** [comment]
share your log from SD card.

**Comment by HeinanCA** [comment]
[MU1440-JTH-07605.05.183402019C.log](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/10892246/MU1440-JTH-07605.05.183402019C.log)

Attached the logs :)

**Comment by harman-f** [comment]
My hacked patched worked like it should.
In case of external amp the change in coding seems to be not effecting the controls.

This must be controlled by dataset in external amp.

**Comment by HeinanCA** [comment]
Sorry for the noob question - can I somehow explore the dataset of the external AMP module?
Reminding I currently don't hold VCP..

**Comment by harman-f** [comment]
I do not have any on hand
