### ISSUE TITLE
Lost car's images

### ISSUE THREAD

**Issue by MuchaZ** [Mr-MIBonk/M.I.B._More-Incredible-Bash#143]
Hi,

After playing with MIB I've lost images of the car (eg. in the top menu and while parking). Any ideas?

Audi A5 Quattro
MHI2_ER_AUG22.K3346
1438

**Comment by harman-f** [comment]
sounds like you messed araounf with coding...

M.I.B. -> Restore

`restore storage .raw - datasets from backup`

**Comment by MuchaZ** [comment]
Thanks @harman-f for the reply. Is there a different way, if not having that backup?

**Comment by harman-f** [comment]
Restore backup from NAND. 
You will find a new folder in Backup on SD card. 
copy all files one directory level up.

**Comment by MuchaZ** [comment]
You mean "restore backup from unit to SD" from this menu, right?


![](https://user-images.githubusercontent.com/98130152/174409163-33cae45e-1332-4904-8ea4-28bdad5c3290.png)

**Comment by harman-f** [comment]
![grafik](https://user-images.githubusercontent.com/98130152/224821660-8bdc8f9e-66cb-4b44-9d12-f0c5c94118c8.png)
