### ISSUE TITLE
Activate audi drive select in audi a4 b9

### ISSUE THREAD

**Issue by Leor2208** [Mr-MIBonk/M.I.B._More-Incredible-Bash#147]
Hi team,
I would like to say thanks for your job, is amazing.
I have another challenge for you.
In audi a4 b9 with mhi2q exists cars that can select drive select mode (dynamic, sport, custom) and this selection can be done in mhi2 menú BUT you need to have a special physical buttons to use this function. Exist a coding to active this carisma menu but in mmi with the coding you cannot select the audi drive menu. Could you study the posibility of activate this menu?
Best regards!
Leo

**Comment by Leor2208** [comment]
![](https://www.audisport-iberica.com/foro/uploads/monthly_2018_12/Capture.JPG.8cf36fa4adaf6950691a98ff5f00778f.JPG)

**Comment by Leor2208** [comment]
This is the menu that we would like to activate in mih2q.
Maybe the name is carisma, maybe ADS or audi Drive Select.
By obdeleven you can activate the menus but it doesnt appear.
Thanks

**Comment by Leor2208** [comment]
This is not a issue, sorry

**Comment by harman-f** [comment]
the menu on MHI2Q is just some coding.

But there is more to be done outside of the 5F to get this going ;)

**Comment by Leor2208** [comment]
We can do something?

**Comment by harman-f** [comment]
If you can find out the required coding or adaptions
