### ISSUE TITLE
Video playing not available anymore 

### ISSUE THREAD

**Issue by Fambalean** [Mr-MIBonk/M.I.B._More-Incredible-Bash#149]
Hi. After playing with my audi mib2 unit my video dvd stop playing and jukebox is greyed out. Any thoughts? Helpppp
I don't know what I've messed up, and i also deleted mib from the memory card and reinstall it , but no luck. 
Can anyone help?

**Comment by harman-f** [comment]
do you still have the backup from SD?

**Comment by Fambalean** [comment]
No. I've deleted the backup by mistake and know I'm in the dark. Everything used to work before, including the video in motion, but i belive that I've done something which I should not have.
When connecting with Odis or Vcds, 5F modul doesn't connect.
Cam I simply reflash it to initial factory firmware?
Is there something I can do to reverse this?

**Comment by harman-f** [comment]
Restore backup from unit

**Comment by Fambalean** [comment]
How I can do that? What is the procedure?

**Comment by Fambalean** [comment]
I haven't got any original back-ups, as I deleted them by mistake

**Comment by harman-f** [comment]
restoring backup from NAND is a M.I.B function.

M.I.B. -> Restore

restore backup from unit to SD

you will find a new folder in /backup/ on SD card

Copy all files one lvl up into /backups/

and run: restore storage .raw - datasets from backup

All coding will be restored to the time of your M.I.B installation

**Comment by Fambalean** [comment]
Thanks. I will try this tomorrow and get back with an update/status. Much appreciated your help

**Comment by Fambalean** [comment]
Hi. I've tried the process you said, but i still have the same issue. There was a folder, I've restored from it, but the issues with the jukebox being grey out and videos not playing are still present.
Any more help?

**Comment by Fambalean** [comment]
Maybe im doing something wrong? I've created a new folder inside backup called backups and I moved the files there. Then I run: restore storage .raw - datasets from backup, but stil the issues are there.
Helppppp

**Comment by harman-f** [comment]
I did not say anything about a new folder...

Just copy all files to /backup/MU... folder

**Comment by Fambalean** [comment]
But they are already there, or at least that MU... folder is there and is populated. I've done that. Still nothing

**Comment by Fambalean** [comment]
I didn't need to copy anything as the file MU.. was already in the backup and all I've done was to : restore storage .raw - datasets from backup, but still nothing, it didn't work. 
Any other options I can do?

**Comment by harman-f** [comment]
please share your log file.

**Comment by Fambalean** [comment]
Please check attached. With regards, Andrei Balean M: 0742 741 8951
-------- Original message --------From: harman-f ***@***.***> Date: 19/03/2023  20:18  (GMT+00:00) To: "Mr-MIBonk/M.I.B._More-Incredible-Bash" ***@***.***> Cc: Fambalean ***@***.***>, Author ***@***.***> Subject: Re: [Mr-MIBonk/M.I.B._More-Incredible-Bash] Video playing not available anymore  (Issue #149) 
please share your log file.

**Comment by harman-f** [comment]
attachment did not work

**Comment by Fambalean** [comment]
I believe it's working now

**Comment by harman-f** [comment]
From your log:
Unit was already patched before the log was generated.
```
RCC-backup---->
recover backup from unit......
 -> done :-)

RCC-restore---->
restore storage .raw.........
 -> done :-)
```

restore worked.
Hence, what ever you messed up must be outside the datasets stored on storage_.raw

**Comment by Fambalean** [comment]
Correct. That is why I've said to you on the first place that I've done some coding and then deleted the sd card by mistake.
Is there anything i can do in this situation?
Can I reflash the unit with a stock fill?

**Comment by harman-f** [comment]
the backup you restored was created and stored on unit the 1st time you installed M.I.B.

That is all I can do.
Normally this backup contains coding and adaption, so no idea was got messed up here.
The resore should have fixed it.

**Comment by Fambalean** [comment]
So, is there another way to restore to stoke firmware using what I've got?

**Comment by Fambalean** [comment]
The backup I've restored and you see was created second time, as first time I thought that it didn't work so I've deleted mib and reinstall it on sd card and obviously something went wrong. 
I've tried everything but no luck, that is why i come to you as you are the wizard in this and i thought that maybe there is another why to re-install stock firmware from what I've got done to the unit now.
Is there any way to do that?

**Comment by Fambalean** [comment]
Ok. I didn't realise that, but also before i done any coding and mib, the unit played dvds, played usb sticks that is why I'm asking you all this questions. 
Maybe the unit gine bad for some reason.
I can't remember what have I done.
Maybe unit needs replacing or maybe video aren't supposed to play anymore on that unit.
Sad that is, but nothing I can do apart from replacing the whole unit and recoding it to the car.

**Comment by harman-f** [comment]
This sounds more like coding gone wrong.
Patching is not touch any coding despite enbaling CP/AA.

Try MIB2 telegram channel, maybe someone has an idea over there.

**Comment by Alussu** [comment]
I had the same problem it happened trying tweeting zVIM. At one point I managed to reset it by restoring obdeleven backup of 5f, it happened again and this time nothing works. I will try to proceed with suggested restoring from unit.
