### ISSUE TITLE
Couldn't patch 4M Q7

### ISSUE THREAD

**Issue by angrycatmeowmeow** [Mr-MIBonk/M.I.B._More-Incredible-Bash#158]
Tried to patch_ifs_root_aio and it said it's only available for stock firmware. Everything worked good up until then.

https://drive.google.com/file/d/1TnWXPxRvsHlL3DrxK9XsHsWX_2KeKj1d/view?usp=sharing
[MU0692-JTB-07407.10.1611840A6C.log](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/11065096/MU0692-JTB-07407.10.1611840A6C.log)

``` 
__  __     ___           ___  
|  \/  |   |_ _|         | _ ) 
| |\/| |    | |          | _ \ 
|_|  |_|ore|___|ncredible|___/ash - V3.5.0 "Spring Edition"
______________________________________________________________________

NOT FOR COMMERCIAL USE - IF YOU BOUGHT THIS YOU GOT RIPPED OFF

Logging_MU0692-MHI2_US_AUG22_P3252-JTB-07407.10.1611840A6C:
HW Number: 052 - PN: 4M0035880B
Variant: FM2-P-TNSL-US-AU-MLE
EEPROM Variant: MU-P-LNS-US
Dataset Version: 4M0909545J
Model ID: 013706 - Car Model: Audi Q7 (4M0)
```

**Comment by Rohansinghdavid** [comment]
I'm in the same boat. I tried on my 2018 Q5 with software MHI2_US_AUG22_P3252. I reached out to @Mr-MIBonk  with the backup and log data but not received any response yet. Still waiting.

**Comment by angrycatmeowmeow** [comment]
Yeah P3252 is where I'm at. Guess there's no patch for that FW. Can we update our own FW?

**Comment by Rohansinghdavid** [comment]
I don't know. I'm waiting for experts like @Mr-MIBonk to reply and help me patch my system so that I can update to the latest maps.

**Comment by Rohansinghdavid** [comment]
![Screenshot_2023-03-24-14-06-39-28_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/127570492/227605818-4866dbf4-97ef-4219-86a2-7dc674dae2ca.jpg)
![Screenshot_2023-03-24-14-07-04-94_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/127570492/227605825-8ccf23f4-366b-4ac5-af19-5727dd74eb56.jpg)
![Screenshot_2023-03-24-14-07-28-60_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/127570492/227605828-70eff3bd-83a0-4ec9-bf99-c093b8ca8b87.jpg)

**Comment by harman-f** [comment]
Well, so far there is just no patch for MHI2_US_AUG22_P3252 included in M.I.B.

Why not update to MHI2_US_AUG22_K3347_MU1439?

**Comment by harman-f** [comment]
`SupportedTrains = "MHI2_US_AUG22_P3252*,MHI2_US_AUG22_K3336*,MHI2_US_AUG22_K3338*,MHI2_US_AUG22_K3340*,MHI2_US_AUG22_K3345*"
`

**Comment by Rohansinghdavid** [comment]
@harman-f thanks for the reply. How do I update it to MHI2_US_AUG22_K3347_MU1439? Could you please help?

**Comment by harman-f** [comment]
Your steps are correct. 

Mibsolution.one for files

**Comment by Rohansinghdavid** [comment]
Thank you very much @harman-f . Will try it today and update you.

**Comment by angrycatmeowmeow** [comment]
> Thank you very much @harman-f . Will try it today and update you.

Let me know how it goes. I may give it a shot too.

**Comment by Rohansinghdavid** [comment]
Will do @angrycatmeowmeow . @harman-f just to let you know that I have B&O music system, do I need to take any precautions?

**Comment by harman-f** [comment]
BOSE is an issue, I know that, not sure about B&O.

**Comment by angrycatmeowmeow** [comment]
I have the Bose, which I guess requires a new meta file?

**Comment by Rohansinghdavid** [comment]
Ok. So if something goes wrong with B&O, can is switch back to older software version and make the B&O work correctly? Is this an option?

**Comment by Rohansinghdavid** [comment]
Hi @harman-f . I updated the firmware to MHI2_US_AUG22_K3347_MU1439 and then installed MIB but still not able to patch. It is taking the patch from the backup folder instead of the patch folder. I don't know why. Any suggestions?

**Comment by Rohansinghdavid** [comment]
Hi @harman-f . I was able to patch finally. Thank you very much. It actually took the the patch MHI2_US_AUG22_K3345_MU1439 for firmware MHI2_US_AUG22_K3347_MU1439. Initially I had copied only one patch which are relevant. Later I copied all the patches to the SD and it automatically selected MHI2_US_AUG22_K3345_MU1439. I just have to update the maps now. Thank you very much again. Cheers!

**Comment by Rohansinghdavid** [comment]
Hi @harman-f . I have an issue now. I tried the navignore to have the maps in VC while connected to Google maps via android auto. And as soon as I ran this the system is not booting at all. Please the attached video. It flickers and says initializing but later shuts off. I tried the MMI reset but again the flickering start for a while and then goes blank. Please help.  Thanks in advance. Rohan

**Comment by harman-f** [comment]
Please Share your log file and a screenshot/picture of the output.

**Comment by Rohansinghdavid** [comment]
Hi @harman-f . I created a new issue for my concern. Please see the below link.  
https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/issues/163
It has the log, backup and a video that I took.  
Please let me know if you need any further information.  

Thanks again for always responding to my concerns. 

Best regards. 
Rohan.
