### ISSUE TITLE
NAR 23 FEC issues not listed as compatible

### ISSUE THREAD

**Issue by jmaco3** [Mr-MIBonk/M.I.B._More-Incredible-Bash#161]
**Describe the bug**
Cannot get the map to update— my version does not appear to be one listed in your compatability section. Thanks for all your awesome work this place is great!

**Check known issues before reporting**
Make sure you have checked here:
https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/wiki/Prepare-M.I.B-SD-card-&-install-M.I.B#%EF%B8%8F-trouble-shooting-%EF%B8%8F

**Add M.I.B LOG file to your report**
Always attach your M.I.B LOG file!
Check M.I.B SD card in folder `/backup/logs/` and upload that file together with your report.

```
 __  __     ___           ___  
|  \/  |   |_ _|         | _ ) 
| |\/| |    | |          | _ \ 
|_|  |_|ore|___|ncredible|___/ash - V3.5.0 "Spring Edition"
______________________________________________________________________

NOT FOR COMMERCIAL USE - IF YOU BOUGHT THIS YOU GOT RIPPED OFF

Logging_MU1118-MHI2Q_US_AUG22_P4171-JTB-07429.08.17118209DB:
HW Number: 034 - PN: 8W5035880A
Variant: FMQ-P-TNSL-US-AU-MLE
EEPROM Variant: MU-P-LNS-US
Dataset Version: 8W2909545H
Model ID: 019453 - Car Model: 
```
[MU1118-JTB-07429.08.17118209DB.log](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/11070701/MU1118-JTB-07429.08.17118209DB.log)

**Screenshots**
E. g. of the error message on screen.

**Additional context**
Was the unit worked on before?
Is the unit stock in car or a retrofit?

**Comment by harman-f** [comment]
Looks like you did not copy the patch to SD card.

RTFM
https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/wiki/Prepare-M.I.B-SD-card-&-install-M.I.B#add-patch-files
