### ISSUE TITLE
VIM Not Active 

### ISSUE THREAD

**Issue by errornt** [Mr-MIBonk/M.I.B._More-Incredible-Bash#169]
#I have problem with toolbox 3.5.0. 

Unit ID MHI2Q_ER_AUG22_P4212
MU-SW 1177

CarPlay and FEC was okay I made maps update, but VIM doesn’t work. 
it says all done, system reboot. 

But after trying it, still same,  6kmh. 
![Uploading C01EAE66-2C71-41D0-8A63-3FCB6181543C.jpeg…]()

**Comment by errornt** [comment]
![Uploading 5BC8A783-E5C2-4445-894F-E29D34308359.jpeg…]()

**Comment by harman-f** [comment]
Well known bug in FW 😢

**Comment by errornt** [comment]
> 

Solution? I have plans to try with older version of Toolbox. 
Should work?

**Comment by harman-f** [comment]
No, will not help!

issue is not related to M.I.B. 
the FW itself has this bug, that changed to VIM do not have any effect.

**Comment by errornt** [comment]
> No, will not help!
> 
> issue is not related to M.I.B. the FW itself has this bug, that changed to VIM do not have any effect.

Understand. 
Thx for info. 🍻
