### ISSUE TITLE
stuck in startup picture , help~

### ISSUE THREAD

**Issue by ilbefun** [Mr-MIBonk/M.I.B._More-Incredible-Bash#17]
when MIB just installed ,  everything ran well. GEM shows well
but after some scripts(navigation ignore & startup picture change) run and reboot, the unit stuck in starup picture, 

meanwhile , the radio sound is still working,  carplay music still works when phone connected, navi in dashbord works ok too,
it seems some error in display in unit screen and stunk in startup pic. even when I  try to press MENU button to enter service menu.

what should I do to recover the unit , thanks!

I will upload the logs  and backup files later
<img src='https://user-images.githubusercontent.com/501298/178395839-a5431f0b-7b92-4874-8f5c-fee62ece5722.jpg' >

**Comment by ilbefun** [comment]
https://drive.google.com/file/d/1bBezSZlcW7ChEXsucS6OiiESvBBXqqBL/view?usp=sharing

**Comment by harman-f** [comment]
That could already be it. 

Do you have access to any OBD tool?

I will have a look into your backup tonight.

**Comment by ilbefun** [comment]
I have a 5053 cable and odis, is that useful?

**Comment by harman-f** [comment]
Yes, you can change long coding with that.

**Comment by ilbefun** [comment]
![image](https://user-images.githubusercontent.com/501298/178481920-8eeef1e5-c446-4d82-8994-30c0af2b4fb3.png)
the 18th bit of 5F is 00 there , and after I change it to 04, startup screen add a new pic "blue motion" before the vw logo still be stuck in.

**Comment by harman-f** [comment]
Your original dataset from backup: `02233612ff00000051150001001c29201f0300e471a00200fc`

Byte | hex value | Bits | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
0 | 02 | 00000010 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 0
1 | 23 | 00100011 | 0 | 0 | 1 | 0 | 0 | 0 | 1 | 1
2 | 36 | 00110110 | 0 | 0 | 1 | 1 | 0 | 1 | 1 | 0
3 | 12 | 00010010 | 0 | 0 | 0 | 1 | 0 | 0 | 1 | 0
4 | ff | 11111111 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1
5 | 00 | 00000000 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
6 | 00 | 00000000 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
7 | 00 | 00000000 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
8 | 51 | 01010001 | 0 | 1 | 0 | 1 | 0 | 0 | 0 | 1
9 | 15 | 00010101 | 0 | 0 | 0 | 1 | 0 | 1 | 0 | 1
10 | 00 | 00000000 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
11 | 01 | 00000001 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1
12 | 00 | 00000000 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
13 | 1c | 00011100 | 0 | 0 | 0 | 1 | 1 | 1 | 0 | 0
14 | 29 | 00101001 | 0 | 0 | 1 | 0 | 1 | 0 | 0 | 1
15 | 20 | 00100000 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0
16 | 1f | 00011111 | 0 | 0 | 0 | 1 | 1 | 1 | 1 | 1
17 | 03 | 00000011 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 1
18 | 00 | 00000000 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
19 | e4 | 11100100 | 1 | 1 | 1 | 0 | 0 | 1 | 0 | 0
20 | 71 | 01110001 | 0 | 1 | 1 | 1 | 0 | 0 | 0 | 1
21 | a0 | 10100000 | 1 | 0 | 1 | 0 | 0 | 0 | 0 | 0
22 | 02 | 00000010 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 0
23 | 00 | 00000000 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
24 | fc | 11111100 | 1 | 1 | 1 | 1 | 1 | 1 | 0 | 0



Byte 17 was originally 3 and is 4 now
Byte 18 was 0 all the time

Try to set byte 17 back

**Comment by ilbefun** [comment]
A china suv model ：vw tayron
Like another version of Tiguan🤭

I saw some error happened when naviignore,could this be fixed?

**Comment by harman-f** [comment]
Yes, if navignore is the issue we most likely also have a fix for that 😉. 

Try coding 1st.

**Comment by ilbefun** [comment]
issue fixed after coding ,many thanks!
I mean navignore didn't work, could this be fixed to work?

**Comment by harman-f** [comment]
Better remove navignore from unit.

Yes, AIO patch should be run 1st
