### ISSUE TITLE
ABOUT PATCH

### ISSUE THREAD

**Issue by INH888** [Mr-MIBonk/M.I.B._More-Incredible-Bash#170]
Patch folder needs to add new version,MHI2_CN_VW48x_P1102_MU1102 needs to be supported...
PLEASE PLEASE my G.O.A.T

**Comment by INH888** [comment]
Or do you have the 7720 version of China map?

**Comment by INH888** [comment]
Or do you have a map of China with the map version code 7720? Thank you very much!

**Comment by harman-f** [comment]
Upload your backup to mibsolution.one
You can also check maps there.

**Comment by INH888** [comment]
> Upload your backup to mibsolution.one You can also check maps there.

Unfortunately, I have tried many times, but the M.I.B.3.5 program does not work successfully on the 1102 version of the MIB048. What should I do?

**Comment by harman-f** [comment]
Please share your M.I.B log and a picture of the error.

**Comment by INH888** [comment]
> Please share your M.I.B log and a picture of the error.

Okay, I'm being stupid. I've uploaded what you need to mibsolution.one

**Comment by INH888** [comment]
> Please share your M.I.B log and a picture of the error.

Dude, any news on patch with firmware version 1102? I want to update the fsc code...Please forgive my poor English. 
Best wishes

**Comment by harman-f** [comment]
Just checked your backup and LOG.
Where do you get stuck?

LOG lokks OK, but does not show any patch attempt!
Backup is only the one from M.I.B install, which does not contain all files.

Run the AIO patch and see what happens. A patch for your FW is already available.
Have you added the patch files to your SD?

https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/wiki/Prepare-M.I.B-SD-card-&-install-M.I.B#add-patch-files
![image](https://user-images.githubusercontent.com/98130152/230706627-a622de58-fa94-4853-989a-68bc0fbaadf7.png)

**Comment by INH888** [comment]
> 



> Just checked your backup and LOG. Where do you get stuck?
> 
> LOG lokks OK, but does not show any patch attempt! Backup is only the one from M.I.B install, which does not contain all files.
> 
> Run the AIO patch and see what happens. A patch for your FW is already available. Have you added the patch files to your SD?
> 
> https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/wiki/Prepare-M.I.B-SD-card-&-install-M.I.B#add-patch-files ![image](https://user-images.githubusercontent.com/98130152/230706627-a622de58-fa94-4853-989a-68bc0fbaadf7.png)

This is the problem, there is no matching software version in this AIO PATCH.Can I use the 0841 version of AIO file![111](https://user-images.githubusercontent.com/130017774/230708846-087ced7d-6854-49ea-86c5-e3a4621f05a7.png)

**Comment by harman-f** [comment]
Check patch archive on mibsolution.one in a bit.
Patch should be there.

**Comment by INH888** [comment]
> 稍后检查mibsolution.one上的补丁存档。补丁应该在那里。

![1680965878439](https://user-images.githubusercontent.com/130017774/230728164-99d9cd09-24f3-48ed-a709-276b4c7df40c.png)
Sorry, it was my fault earlier, wasting your precious time, not reading all the instructions on M.I.B. Now, I have uploaded the firmware backed up by m.i.b to the m.i.b_backup folder again, please help me make the patch, thank you very much again, please forgive my bad English, my good brother.

**Comment by INH888** [comment]
> 稍后检查mibsolution.one上的补丁存档。补丁应该在那里。

Thank you! The AIO patch is working! Love you!
