### ISSUE TITLE
Path support MHI2Q_US_AUG22_P3639_MU0918 version ?

### ISSUE THREAD

**Issue by quxin5605** [Mr-MIBonk/M.I.B._More-Incredible-Bash#174]
The M.I.B_patches_2023_04_08.7z Patch folder does not contain MHI2Q_US_AUG22_P3639_MU0918_PATCH
Please support this version，Thank U so much！

**Comment by harman-f** [comment]
share your backup please

**Comment by quxin5605** [comment]
https://drive.google.com/file/d/1LRs9hMGzmtQavw7v2nYAUg-PSyWQz3fX/view?usp=share_link
Thank U

**Comment by harman-f** [comment]
check mibsoltion

**Comment by quxin5605** [comment]
I get it, Thank you so much
