### ISSUE TITLE
Navignore not working for MHI2_ER_AU57x_K3663 (most likely als not for other 3xxx firmware)

### ISSUE THREAD

**Issue by a82kd** [Mr-MIBonk/M.I.B._More-Incredible-Bash#177]
Navignore jar installs via MIB 3.5.0 without any errors, however, dual nav is still not working.
- Tried AA and CP
- Doesn't matter wheter I start Audi Nav or AA/CP first, it will always stop the other nav tool.
- I tried to uninstall and install again, but no success
- I am running the common AIO package which is running fine. (so I guess others will have this issue as well)

MIB log file attached. (navignore is 3 times in the log since I tried unistall/install again)
[MU1425-JTB-07420.07.1511730FB2.log](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/11222124/MU1425-JTB-07420.07.1511730FB2.log)

**Comment by harman-f** [comment]
AU57x is sadly not supported by current navignore solution
