### ISSUE TITLE
dont see M.I.B. in green menu 

### ISSUE THREAD

**Issue by benassyGT** [Mr-MIBonk/M.I.B._More-Incredible-Bash#183]
Hi, original unit auti TTs 2016 was MHI2_ER_AU43x_P3226 NOW MHI2_ER_AU43x_P5098, after instal M.I.B. launcher and reboot system, there is no M.I.B. in green menu :( only "produciton" . Any solution ? :(

**Comment by harman-f** [comment]
Leave sd card in unit

**Comment by benassyGT** [comment]
Sd card is all time in unit.......

Dne ne 23. 4. 2023 14:01 uživatel harman-f ***@***.***>
napsal:

**Comment by harman-f** [comment]
Share your log file
