### ISSUE TITLE
Installation is successful but M.I.B. - More Incredible Bash does not appear in GEM

### ISSUE THREAD

**Issue by neoalius** [Mr-MIBonk/M.I.B._More-Incredible-Bash#184]
Installation is successful but M.I.B. - More Incredible Bash does not appear in GEM

BACKUP/LOG FOLDER is empty
![Uploading IMG-0008.jpg…]()
![Uploading IMG-0010.jpg…]()
![Uploading IMG-0011.jpg…]()

**Comment by harman-f** [comment]
Which FW?
Did you leave SD in unit?

**Comment by benassyGT** [comment]
Same issu like u.. on audi

**Comment by neoalius** [comment]
> Which FW? Did you leave SD in unit?

Yes ! SD card was in the card slot while final restart

firmware MHI2_ER_AUG_K3346 MU 1438

**Comment by harman-f** [comment]
please share log file

**Comment by benassyGT** [comment]
How?? If i not run M.I.B???

Dne po 24. 4. 2023 18:06 uživatel harman-f ***@***.***>
napsal:

**Comment by neoalius** [comment]
BACKUP/LOG FOLDER is empty

**Comment by benassyGT** [comment]
> BACKUP/LOG FOLDER je prázdná

Yes, its empty.. mayby try instaling another FW

**Comment by neoalius** [comment]
Issue fixed

Reset the unit to factory except media
Used a different SD card adapter ( made sure it’s not locked) and updated MMI again. Wolla it worked.
