### ISSUE TITLE
Languages Problem with MHI2_ER_AU57x_K3663

### ISSUE THREAD

**Issue by SergeyShevchenko** [Mr-MIBonk/M.I.B._More-Incredible-Bash#191]
**Describe the bug**
Wrong train symbols in script `apps/setlang` for MHI2_ER_AU57x_K3663. It was `"$TRAINVERSION" = *ER_AUG57x*` and therefore when I was trying update visible MMI languages dataset I was getting message: no supported train found - will stop here. After I deleted `G` in `ER_AUG57x` making it `ER_AU57x` it worked like a charm.

**Comment by harman-f** [comment]
Thanks, will be fixed in next release!
