### ISSUE TITLE
Component Protection Active in 5F

### ISSUE THREAD

**Issue by Nathan2090** [Mr-MIBonk/M.I.B._More-Incredible-Bash#193]
Hi~After running AIO, the 5F unit still has a fault code by ODIS: [U110100] Component Protection Active. How can I clear it?

**Comment by lepooo** [comment]
You can not. Fault is also in the unit 19, gateway. Only solution for this is remove component protection via online geko.

**Comment by Nathan2090** [comment]
> 

OK~get it. Thanks!

**Comment by Nathan2090** [comment]
> You can not. Fault is also in the unit 19, gateway. Only solution for this is remove component protection via online geko.


Ok~get it. Thanks!
