### ISSUE TITLE
MAP update ERROR : No valid update data 

### ISSUE THREAD

**Issue by neoalius** [Mr-MIBonk/M.I.B._More-Incredible-Bash#200]
**Describe the bug**

Unable to update MAPs, ERROR : No valid update data. 
Unit Patched with FEC 
S/W : MHI2_ER_AUG_K3346_MU1438

**Add M.I.B LOG file to your report**
[MU1438-JTB-07428.05.16119300F9.log](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/11413667/MU1438-JTB-07428.05.16119300F9.log)

**Screenshots**
![IMG-0041](https://user-images.githubusercontent.com/131591423/236652413-91b2868e-1b7e-42f6-a5cc-32bd5f238b67.jpg)
![IMG-0042](https://user-images.githubusercontent.com/131591423/236652417-c8a56eef-92da-43c1-baa1-608339b628a3.jpg)
![IMG-0045](https://user-images.githubusercontent.com/131591423/236652418-c6c9494e-01ef-4aef-a807-fb34f5cc2d02.jpg)
![IMG-0046](https://user-images.githubusercontent.com/131591423/236652419-90c30d9c-6d96-4239-a2a8-8994032327ea.jpg)

**Additional context**
Tried updated in REM
Reads NAV update but not possible to start update.
![IMG-0043](https://user-images.githubusercontent.com/131591423/236652445-4770ab84-8414-4eaf-94e7-ebd67f33c424.jpg)
![IMG-0044](https://user-images.githubusercontent.com/131591423/236652448-2b85a356-c984-4a1d-9be9-53500e60e187.jpg)

Country is Australia and genuine NAV DB FEC is 023D0020 

SD cards is 64 Gb exFAT format 
<img width="346" alt="Screenshot 2023-05-07 at 10 48 03 am" src="https://user-images.githubusercontent.com/131591423/236652620-2680e121-9f85-472b-90e2-3c74eca3e031.png">

**Comment by neoalius** [comment]
Update started after replacing 023000EE with 023D00EE

**Comment by harman-f** [comment]
SDS also has to be switched. 

FEC and coding have to be all correct to allow map install. 
unit was EU before?
You might need to delete maps on unit. 
there is a function in M.I.B

**Comment by sadahsan** [comment]
> Update started after replacing 023000EE with 023D00EE

How did you replace it?

**Comment by sadahsan** [comment]
> SDS also has to be switched. ![grafik](https://user-images.githubusercontent.com/98130152/236665468-a2c1d3ff-6ef6-4eb4-a2d6-24a5c2703509.png)
> 
> Which maps are you trying to install?
> 
> FEC and coding have to be all correct to allow map install. unit was EU before?
> 
> You might need to delete maps on unit. there is a function in M.I.B

How to delete old maps?
I have converted the unit from Japan to EU and added FEC code for EU (023000ee) but how shall I remove the Japanese FEC code (02330026) its still visible in the list as legal.

I would like to delete it completely please.
