### ISSUE TITLE
Final Script Take to Long to Execute 

### ISSUE THREAD

**Issue by R3DcooDe** [Mr-MIBonk/M.I.B._More-Incredible-Bash#206]
Hello

Audi A6 2016 Imported from Korea
It has MHI2_KR_AU57x_S0035

I try to install M.I.B via sd Card ( Note i this problem occurs many time i use in 4 diferent cars Audi A6 same version)  with diferent sd cards new ones

Problem is when intry to install mib,  unit stuck on final script for long time. After it shows an errorr se photo below.   After i press try again unit restart after some times. At final screen it says LANUCHER OK.  but when i enter green menu there is no MIB,  

So i have to reapet Installling procedure Again.  Same steps red menu sd card only launcher set to yes. Pres update. Wait long time at final script.   After restart mib is installed 
![IMG-20230406-WA0000](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/33391224/5d3924c9-7dfa-43d3-87af-c726e191717d)

![20230510_124205](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/33391224/ac4d27f6-aeb7-4ae2-bbdf-af1fab125220)

**Comment by harman-f** [comment]
This is a very old FW ;)

Try latest version from repo: https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/archive/refs/heads/main.zip
It just added some initial support for these old FW. Not all M.I.B functions are working, but the most basic stuff might now ;)

Please run it and share the log file from SD

**Comment by R3DcooDe** [comment]
Hello Mate, thank you for your great work,  here in my country all cars almost are with old firmwares :/  i use mib to convert to Europe version, and install European Firmware.  
Here are logs for today region Convert. Korean firmware and European Firmware 

[MU0035-AW7-MON05.10.1500060674.log](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/11444357/MU0035-AW7-MON05.10.1500060674.log) -- Korea

[MU1425-AW7-MON05.10.1500060674.log](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/11444359/MU1425-AW7-MON05.10.1500060674.log) -- Europe

**Comment by harman-f** [comment]
So it did work in the end?

**Comment by R3DcooDe** [comment]
yess well done sir well done, keep up the great work.   if you have some time, can i contact you somewhere else, to discus about mib2+ mib3 solutions :D  i have telegram Tahyp Lala and email address r3dcoode@outlook.com   thank you :)
