### ISSUE TITLE
Need help on patching ifs-root

### ISSUE THREAD

**Issue by zzz08900** [Mr-MIBonk/M.I.B._More-Incredible-Bash#212]
I was trying to add FEC to my MHI2 unit but so far no luck. My MHI2 unit seems to  be a rather strange unit with the following SW Train: MHI2_CN_VW511_P1002. 
I managed to install M.I.B and applied the navignore patch, also map update from mibsolution.one works.

My end goal is to build a ifs-root patch for my unit. So is there any patch-building how-to laying around?
I already uploaded my backup to mibsolution.one, if necessary I could share it here too.

I'm attaching a few pictures of my unit so people can see that I didn't the get SW Train wrong. :)

![IMG_0583](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/51951532/642d1771-0f47-4398-9c18-075b22806895)
![IMG_0584](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/51951532/dd66f985-a2bc-405f-bfe4-5c3669965bfe)
![IMG_0586](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/51951532/b70c9c71-13b5-4093-88c0-08c0ab9e1b64)

**Comment by harman-f** [comment]
get a backup please

**Comment by zzz08900** [comment]
> get a backup please

A backup zip along with its logs are already uploaded to https://mibsolution.one/#/1/14
Filename: MU1002-MHI2_CN_VW511_P1002-AW7-MON22.08.1800061022.zip ---> the backup zip
Filename: MU1002-AW7-MON22.08.1800061022.log ---> the log file

**Comment by harman-f** [comment]
1st time I see this train.
Could someone already changed this?

**Comment by zzz08900** [comment]
> 1st time I see this train. Could someone already changed this?
> 
> Which car model is it?

Well, I did a few map updates and applied navignore patch. Everything else should be factory.
The car is a 2018 Phideon, a SAIC-VW special that's (afaik) only sold in China.

**Comment by harman-f** [comment]
Check M.I.B folder on mibsolution ;)

**Comment by zzz08900** [comment]
> Check M.I.B folder on mibsolution ;)

Will test it tomorrow. You are really a miracle worker.
A thousand thanks.

**Comment by zzz08900** [comment]
Tested and verified that the patch works. I have successfully added sport-MHI FEC to my MHI2 unit. 
The only reading I can get from sport-MHI is coolant temp - no surprise here since sport-MHI was never meant for my car model.
