### ISSUE TITLE
Header seize on unit does not match patch files seize

### ISSUE THREAD

**Issue by junibuNn** [Mr-MIBonk/M.I.B._More-Incredible-Bash#216]
Hey,
I tried to flash my unit with the patched fw i got from mibsolution "MHI2_ER_AUG22_P3241_MU0678".
Unfortunately I get this Error message...

[MU0678-JTB-07413.09.161190031C.log](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/11511165/MU0678-JTB-07413.09.161190031C.log)

best regards

**Comment by harman-f** [comment]
something is off with your patch file.

Show a screenshot of your patch folder please:
patches/MHI2_ER_AUG22_P3241_MU0678_PATCH

**Comment by junibuNn** [comment]
<img width="730" alt="patch folder" src="https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/134009091/3abb5397-5cd2-4b4a-939d-22d27641e98b">

**Comment by harman-f** [comment]
Not sure what you are doing here, but that is 100% wrong. 

Check wiki section here. 
there is a guide on how to setup the SD card.
