### ISSUE TITLE
How can I replace the oem carplay icon on MIB2 high with some SD script?

### ISSUE THREAD

**Issue by Nathan2090** [Mr-MIBonk/M.I.B._More-Incredible-Bash#221]
Hello, is there any way to replace the oem carplay icon on MIB2 high with some SD script? I found it's file path is /etc/eso/media/carplay_oemicon.png, but I cannot replace it with any SD script tools.....

**Comment by harman-f** [comment]
In General icons can be replaced. Methodists are different based on FW/Brand. 

Which train do you have. 

What do you want to replace it with?

**Comment by Nathan2090** [comment]
> In General icons can be replaced. Methodists are different based on FW/Brand.
> 
> Which train do you have.
> 
> What do you want to replace it with?

My software version is MHI2_CN_VW48x_P0841_MU0841, and I want to use the new VW MIB3 CarPlay icon to replace the old one…

**Comment by harman-f** [comment]
carplay_oemicon.png is th eone displayed in CP to go back to your MIBs screen.

The one from the MIB GUI is hidden in a skin file.

mib2toolbox has tools for that:
https://github.com/jilleb/mib2-toolbox/tree/master/Tools

**Comment by Nathan2090** [comment]
> carplay_oemicon.png is th eone displayed in CP to go back to your MIBs screen.
> 
> The one from the MIB GUI is hidden in a skin file.
> 
> mib2toolbox has tools for that: https://github.com/jilleb/mib2-toolbox/tree/master/Tools

Yes, I know those tools and the MIB GUI can be moded by them. But the icon (VW logo) displayed in CarPlay home page is located in /etc/eso/media/carplay_oemicon.png as I found. Can I replace it with some SD scripts?

**Comment by Nathan2090** [comment]
> carplay_oemicon.png is th eone displayed in CP to go back to your MIBs screen.
> 
> The one from the MIB GUI is hidden in a skin file.
> 
> mib2toolbox has tools for that: https://github.com/jilleb/mib2-toolbox/tree/master/Tools

Yes, I know those tools and the MIB GUI can be moded by them. But the icon (VW logo) displayed in CarPlay home page is located in /etc/eso/media/carplay_oemicon.png as I found. Can I replace it with some SD scripts?

**Comment by harman-f** [comment]
![carplay_oemicon](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/98130152/bf34b8fc-7989-4771-8096-5054bd87a205)

![grafik](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/98130152/4d234769-b734-4436-93c5-45904f2a22c4)

Create a script file called: `command.sh`
and place it in `/mod/` on SD card

You can the script from GEM
`Main -> M.I.B. -> Advanced Settings -> Individual Script`

**Comment by Nathan2090** [comment]
> ![grafik](https://user-images.githubusercontent.com/98130152/239820352-04de453e-b92b-44ad-b78e-30140704a880.png)
> 
> Create a script file called: `command.sh` and place it in `/mod/` on SD card
> 
> You can the script from GEM `Main -> M.I.B. -> Advanced Settings -> Individual Script`

Okay, I'll try this. Thanks a lot.

**Comment by harman-f** [comment]
How does the MIB 3 icon look like?

**Comment by Nathan2090** [comment]
> How does the MIB 3 icon look like?

![carplay_oemicon](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/112721209/62b1b5f8-17dd-4065-b675-7fc212890ed5)
like this one...

**Comment by harman-f** [comment]
Ah, you want the new logo tyle ;)

![grafik](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/98130152/adbe5157-63b7-48b5-83ac-6c8a1e6cae1c)

**Comment by Nathan2090** [comment]
> Ah, you want the new logo tyle ;)
> 
> ![grafik](https://user-images.githubusercontent.com/98130152/239822649-adbe5157-63b7-48b5-83ac-6c8a1e6cae1c.png)
> 
> In case you need the old one: [carplay_oemicon.zip](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/11527798/carplay_oemicon.zip)

thanks :)
