### ISSUE TITLE
After modified the shadow.txt to replace the root password, the unit reboot every 60s....

### ISSUE THREAD

**Issue by Nathan2090** [Mr-MIBonk/M.I.B._More-Incredible-Bash#223]
Hello~~After modified the shadow.txt to replace the root password, the unit reboot every 60s. The unit can enter the system menu and can be operated, but automatically reboots every 60s....How can I fix it?

**Comment by harman-f** [comment]
With M.I.B function?

Please share LOG file

**Comment by Nathan2090** [comment]
> With M.I.B function?
> 
> Please share LOG file

actually, I patched it with mib2-toolbox....

**Comment by zzz08900** [comment]
Looks like some kind of system integrity protection stuff. Try place the original file back maybe?

**Comment by harman-f** [comment]
That could sadly be the case. 
was the unit patched before?

please Share your backup from SD.

**Comment by zzz08900** [comment]
Just asking, does these systems has a flash chip that can be re-programmed by an external chip programmer?
Or is the unit doomed if we mess up something in a rather bad way?

**Comment by harman-f** [comment]
There are levels of bad 😉 
Many can be recovered.

**Comment by zzz08900** [comment]
OK I got it. There's no "last resort one key reset all" around.

**Comment by Nathan2090** [comment]
> That could sadly be the case. was the unit patched before?
> 
> please Share your backup from SD.

It's just an original shadow file....
[shadow.txt](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/11544280/shadow.txt)

**Comment by zzz08900** [comment]
You could try the on-board telnet connectors but they may not work. My guess is telnet related stuff is what triggers integrity protection.

**Comment by Nathan2090** [comment]
> You could try the on-board telnet connectors but they may not work. My guess is telnet related stuff is what triggers integrity protection.

May be you are right. The root password is protected by some security mechanism on my unit.
