### ISSUE TITLE
20230412_M.I.B_Patches，not found  my car version

### ISSUE THREAD

**Issue by JianJingGao** [Mr-MIBonk/M.I.B._More-Incredible-Bash#227]
**I didn't find the corresponding version patch for my car, is this normal, thank you**
![微信图片_20230525212712](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/51236891/fe54dde2-7b9c-4703-9582-f6deda9e34c3)

**Comment by harman-f** [comment]
Share backup from SD card
ZIP --> filehorst.de
