### ISSUE TITLE
MHI2_KR_AUG11_P0009

### ISSUE THREAD

**Issue by R3DcooDe** [Mr-MIBonk/M.I.B._More-Incredible-Bash#232]
Hello Sir Please can you add basic functions for this old firmware also 

MHI2_KR_AUG11_P0009 -->  Audi A7 2016 / imported from Korea 

I need just ability to convert to European Firmware 

Thank you

**Comment by harman-f** [comment]
As long as code is not merged, you can try @Iprot fork:
https://github.com/lprot/M.I.B._More-Incredible-Bash
Get in contact with him.

**Comment by R3DcooDe** [comment]
hello sir, thanks for your time, how to contact with him thank you
