### ISSUE TITLE
Memories screen layout changed after subwoofer activation

### ISSUE THREAD

**Issue by andreabafile** [Mr-MIBonk/M.I.B._More-Incredible-Bash#234]
The image layout of the memory buttons displayed on the screen sometimes get changed after subwoofer activation. 
See pictures attached.
Unit MHI2Q
Audi A5

![EDC97AC4-E5F2-4D9F-BAF0-5B6259AAD56B](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/109160754/40bccdfe-cb00-443e-a09a-a28aeb116489)
![33BD295D-4443-4669-900C-5A00A35CC258](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/109160754/1a1ea6c8-a7fb-463d-a001-baf9063673a4)

**Comment by harman-f** [comment]
interesting, how did it look before?

**Comment by andreabafile** [comment]
Attached the correct one for my A5. 
![9A12E051-3936-4955-8615-12C3FF7635D5](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/109160754/2a850c03-1557-4ad1-a191-b24627d3d599)

**Comment by harman-f** [comment]
Interesting.
Looks like keypad Lay-out from different model.

**Comment by andreabafile** [comment]
Indeed.
