### ISSUE TITLE
MU0389-MHI2_ER_AU57x_S2519_1 patch

### ISSUE THREAD

**Issue by gardefone** [Mr-MIBonk/M.I.B._More-Incredible-Bash#236]
The patch for this particular SW train is still unavailable in Your collection

Please take a look at my attached Backup file from M.I.B. utility,

https://filehorst.de/d/ekuJJjEJ

Thanks!

**Comment by harman-f** [comment]
That FW is really old ;)

You should update, but be careful with BOSE.
