### ISSUE TITLE
Patch needed for MHI2_US_VWG13_P3662_1 (MU1418)

### ISSUE THREAD

**Issue by mc32768** [Mr-MIBonk/M.I.B._More-Incredible-Bash#237]
I see there is already a patch for MHI2_US_VWG13_P3662, but I have MHI2_US_VWG13_P3662_1 (same thing but with "_1" at the end).  The patch for MHI2_US_VWG13_P3662 does not seem to work on my "P3662_1" device.

I have placed a backup here and attached logs and screen images:
https://filehorst.de/d/eHumgmvw

Is a new patch required for the "_1"?

Thank you for your help!

![20230605_141734](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/135664938/ba1a1cfd-1108-4326-abc0-8494e3c7755f)

![20230605_143043](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/135664938/e86b5ba2-b29a-475b-a413-c55adcc7e76b)

[MU1418-JTB-07419.09.19119403C0.log](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/11657796/MU1418-JTB-07419.09.19119403C0.log)

**Comment by harman-f** [comment]
You can just rename the existing patch folder.

**Comment by mc32768** [comment]
That worked - thank you so much!  This software is amazing and I am very grateful to have access to it.
