### ISSUE TITLE
MOD - error install new skin SKODA

### ISSUE THREAD

**Issue by divacky** [Mr-MIBonk/M.I.B._More-Incredible-Bash#252]
I installed MIB 2.5 new skin on a skoda kodiaq and an error appeared during installation: /net/mmx/fs/sda0/apps/ImageMOD[28]:.:/net/mmx/ts/sda/apps/../config/ HEADER: No such file or directory
can you help me
Thanks

![20230614_204958](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/37082286/caac50c5-074b-40bd-8968-d950b3b3d490)
[MU1440-JTB-07413.06.1911940699.log](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/11749985/MU1440-JTB-07413.06.1911940699.log)

**Comment by harman-f** [comment]
get latest version from repo, should be fixed
