### ISSUE TITLE
Install vwg13 image mod error

### ISSUE THREAD

**Issue by SeMax1337** [Mr-MIBonk/M.I.B._More-Incredible-Bash#264]
![camphoto_758783491](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/48476180/a36f8f64-4285-49de-9b18-846a5cade34c)
![IMG_4630](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/48476180/31292503-30e9-4e8d-9fd9-07e1a5f6f50a)
/net/mm›/fs/sda0/apps/ImageMOD[210]: [: =: missing second argument

**Comment by harman-f** [comment]
try again with latest repo version!
