### ISSUE TITLE
Mhi2_us_aug11_s0533 - Not Supported 

### ISSUE THREAD

**Issue by R3DcooDe** [Mr-MIBonk/M.I.B._More-Incredible-Bash#265]
Hello Sir 

Today i was trying to convert AUDI A6 2016  from USA
with firmware Mhi2_us_aug11_s0533 to EUROPE and install European firmware : MHI2_ER_AU57x k3663 because i couldn't find any update starting with mhi2_er_aug11xxxxx 

I installed mib from sd card to car.  I opened mib i clicked change train to eu.  All stets said done. Until last step said something not found. But it move to fast and restarted i couldn't see what exactly was.      So i run mib again and i clicked 5minute backup so , i will provide back up to you and logs from mib sd card.   I hope you can help me with patch for this unit to successfully convert to europe and install eu maps.  

Thank you 
Backup link here : 

https://www.mediafire.com/file/nx17cfsnkhi3nbm/backup+mib.zip/file

![IMG-20230628-WA0003](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/33391224/cc993d29-0db9-44e2-80dd-411bc9f9b7fb)

**Comment by harman-f** [comment]
AU57x is correct for aug11

Car is in EU now?

Did you do a conversion before installing the EU FW?

**Comment by R3DcooDe** [comment]
@harman-f  yes i installed MIB and clicked conversion to europe. But mib fail to do it last step it says ,  there is no conversion train found PLEASE CONTACT MIB creators for Help.      So car it is with original firmware now.   Please see logs and backup on the link above . 

Thank you

**Comment by harman-f** [comment]
Conversion is not yet merged with main. 
will need a few more days. Currently focusing on flash.

**Comment by R3DcooDe** [comment]
@harman-f  okay sir , so i have to wait a few days. And you will add  this firmware to supported list

**Comment by harman-f** [comment]
please create a fresh M.I.B backup and share (filehorst.de)

I need to check which state the unit is in ;)

**Comment by R3DcooDe** [comment]
@harman-f  here is the link : https://filehorst.de/d/erzekfgi

**Comment by harman-f** [comment]
OK, one of the issues is, that you are using a quite old M.I.B version.
It is not supporting your very old FW.

Get latest version from repo directl, it will support it.

Before converting to EU you should install latest US FW.
M.I.B will fully work here.

To be able to do this you have to edit metainfo2 to enable install over AUG11 train and disable BOSE.

**Comment by R3DcooDe** [comment]
hello mate thank you for your time, i actually tried today this method , i install latest us firmware MHI2_US_AU57x_K3341  and installed mib again, run same steps like always ,  first eu conversation , after step 1, 2 eeprom and 3 reboot,   deleted nav database.  /   now the fun part is when i open red menu to install European firmware .  it says  MHI2_EU_AU57x_K3663 / MU Software 1426 ---- -  on the other hand European firmware on sd card it has MU Software 1425 

now when i go to red menu to update there is no USER DEFINED MODE  its greyed out..  i tick skip region check and enable user defined  at mib advance swdl ..  

now im stuck here cant install european firmware 

![352535106_982772712920280_8066639726252513224_n](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/33391224/b1ea4894-c809-404a-9227-a441ac4469e2)
