### ISSUE TITLE
Navigation icon not displayed.

### ISSUE THREAD

**Issue by Mission-droid** [Mr-MIBonk/M.I.B._More-Incredible-Bash#278]
Hi, added mib with sd, added map updates however there is no sat nav icon displayed on vc. Your help will be greatly appreciated. Audi tt mk3.

**Comment by harman-f** [comment]
Did you have map function before?

Please shar log file

**Comment by Mission-droid** [comment]
No previous map function.
log

[MU1339-JTB-07420.09.1611850E90.log](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/12018576/MU1339-JTB-07420.09.1611850E90.log)

**Comment by harman-f** [comment]
LOG looks OK. Navigation is activated.

For CP/AA your cluster might need an update. Navigation however, should work out of the box.

**Comment by Mission-droid** [comment]
Apologies I'm a newbie, how is the CP/AA cluster updated.
