### ISSUE TITLE
Porsche Bentley not Taking update ?

### ISSUE THREAD

**Issue by graftonskaggs** [Mr-MIBonk/M.I.B._More-Incredible-Bash#293]
Does anyone know why the update doesn't work on the Porsche or Bentley's. I've gotten it to work in the Audi but it says the medium contains no valid update data in the Bentley and Audi Harmon units. Seems to be the exact same head unit.

**Comment by graftonskaggs** [comment]
Maybe there is a different update in the engineering menu. How do you get to this menu on these systems. I tried the one in settings

**Comment by harman-f** [comment]
Check mibwiki.one for key combinations to enter Engineering menu.
