### ISSUE TITLE
Unable to see the MIB menu in Green Engineering Menu

### ISSUE THREAD

**Issue by gkelly147** [Mr-MIBonk/M.I.B._More-Incredible-Bash#294]
**Describe the bug**
Unable to see the menu in Green Engineering Menu (Nav UP and Media UP 5 secs). 

Using ExFAT formatted 64GB SD card to update the following modules using Red Engineering Menu (Nav UP and Media DOWN 5 secs):

- 5F: MHI2_ER_AU43x_P5098_MU1339 (TT).7z (source: [mibsolution.one](http://mibsolution.one/))
- 17: 8S0 906 961 AE - VC 0296 (source: https://drive.google.com/file/d/1no6y6ZxGmQ7smsMFQzIMAfp6dEMNwzhJ/view)

Updates completed as expected through here > https://www.audiworld.com/forums/tt-mk3-discussion-207/my2016-us-tt-carplay-activation-diy-3051673/

17 update I cannot confirm, but I extracted the files from the linked VC 0296 zip file onto the SD card and completed the update process through the Red Engineering Menu. This was the only way the SD card content would be visible. 

**Check known issues before reporting**
Make sure you have checked here:
https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/wiki/Prepare-M.I.B-SD-card-&-install-M.I.B#%EF%B8%8F-trouble-shooting-%EF%B8%8F

**Add M.I.B LOG file to your report**
Always attach your M.I.B LOG file!
[backup.zip](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/12177261/backup.zip)

**Screenshots**

5F Version before updates > 
<img width="436" alt="image" src="https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/77665640/40bd807a-d68e-438f-aa6a-4f5f3f89e7c0">

5F update confirmed here > <img width="686" alt="image" src="https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/77665640/03018bae-98c6-4310-9b47-b0f707784bde">

17 Update in progress > <img width="562" alt="image" src="https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/77665640/dead4a35-c9af-4f17-8a3c-f885cd1ea6dc">

Cannot see MIB option > 
<img width="815" alt="Screenshot 2023-07-26 at 22 47 53" src="https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/77665640/8bdbfe9a-3817-45da-9579-3b2b990447d2">

**Additional context**
Was the unit worked on before?
The previous 5F Version was MHI2_ER_AU43x_P3226 (see screenshot above) but never worked on to my knowledge. 

Is the unit stock in car or a retrofit?
Unit is stock Oct 2016 Audi TT Mk3 (8S)

**Comment by gkelly147** [comment]
One more point, for the MIB Launcher Installer parameter '_Swdlautorun.txt' to 'Swdlautorun.txt'

**Comment by harman-f** [comment]
M.I.B SD is also exFAT?
SD is still in unit?
