### ISSUE TITLE
No GEM Menu after update - MHI2Q

### ISSUE THREAD

**Issue by Julian881** [Mr-MIBonk/M.I.B._More-Incredible-Bash#298]
S5 - 2019 - MHI2Q_ER_AUG22_P5092 - MU 1329

Everything went ok with the update but when i try to open the GEM it goes directly to the red menu like the update didn't take place.
[backup.zip](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/12207739/backup.zip)

Hoping for a solution.  Thank you!

**Comment by Julian881** [comment]
[MU1329-JTB-07404.02.1911730571.log](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/12207755/MU1329-JTB-07404.02.1911730571.log)

**Comment by harman-f** [comment]
LOG file is incomplete.

Get new SD card and install again.
SD has to stay in SD1 to be able to use M.I.B in GEM.

**Comment by Julian881** [comment]
Yes, i kept it in while trying. Getting a new card and trying again today. 

Will let you know of the outcome. Thank you!

**Comment by Julian881** [comment]
[MU1329-JTB-07404.02.1911730571.log](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/12213695/MU1329-JTB-07404.02.1911730571.log)

New card, same thing happened.

**Comment by harman-f** [comment]
Strange, try 3.7.1 release

**Comment by Julian881** [comment]
Tried one more time and  it worked. Thanks!

**Comment by Julian881** [comment]
Now I can’t manage to update fec. I am trying the last version of ROWBest regards,BogdanOn 31 Jul 2023, at 13:49, harman-f ***@***.***> wrote:﻿
Strange, try 3.7.1 release

**Comment by Julian881** [comment]
Best regards,BogdanOn 31 Jul 2023, at 16:59, harman-f ***@***.***> wrote:﻿
Share LOG again.
