### ISSUE TITLE
I can´t see the app connect icon after doing the patch

### ISSUE THREAD

**Issue by ghassan1986** [Mr-MIBonk/M.I.B._More-Incredible-Bash#304]
Hi,

I tried to unlock carplay/Mirrorlink (App-connect) on this porsche for one friend but after everything was done, unfortunately I cant see the app icon, i tried to activate the icon again as separate order using GEM but it didnt help.

Software Info:
MHI2_ER_POG11_P3299

where I can find the logs to attach it here?

**Comment by zzz08900** [comment]
logs should be in your MIB SD card, under the backup folder

**Comment by ghassan1986** [comment]
thx, here are the logs as per the attched links.

https://easyupload.io/67vy3j

that would be very pleasant of you guys to check where is the issue.


Thank you so much!

**Comment by harman-f** [comment]
icons will onl show up after a phone is connected and CP/AA is activated on that phone

**Comment by ghassan1986** [comment]
I tried both Apple and Android with original USB-Cables and both are not working, the icon doesn`t show up at all, do you know what is the issue here and how it can be done?

Thx

**Comment by harman-f** [comment]
You did not install the patch so far:

`Patch folder /net/mmx/fs/sda0/patches/MHI2_ER_POG11_P3299_MU0807_PATCH NOT found on SD card`

Please check instruction in Wiki again ;)

**Comment by ghassan1986** [comment]
It was there, I put it and did the patch 2 times and it shows successful

**Comment by ordekalo** [comment]
change permission of files (from read-only)

**Comment by Maltman3000** [comment]
ghassan1986 can you send me the patch collection MHI2_ER_POG11_P3299 as mibsolution is down?
