### ISSUE TITLE
carplay patch MHI2_ER_VWG13_P4521

### ISSUE THREAD

**Issue by FAOUZISSAM** [Mr-MIBonk/M.I.B._More-Incredible-Bash#305]
BONJOURS

JE SOUHAITE QUEL VERSION PATCH JE PEUT  METTRE SUR MHI2_ER_VWG13_P4521 POUR ACTIVER LA FONCTION CARPLAY ET COMMANDE VOCAL

CDT

**Comment by Cupidstunt79** [comment]
I’d update to the MHI2_ER_VWG13_P4525 AIO firmware and everything you want will be done in one go

**Comment by harman-f** [comment]
https://github.com/harman-f/MHI2_MIB2_AIO_FW_Update_Template/wiki/AIO-installation

**Comment by FAOUZISSAM** [comment]
thank you for your answers but please where i can find the file to download it because it is not available

**Comment by FAOUZISSAM** [comment]
MHI2_ER_VWG13_P4525 AIO version is not available
![Screenshot_20230808_095617_Brave](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/141341776/42b25caa-d364-4dd3-9d18-cce839832e59)
