### ISSUE TITLE
Multiple Bugs Spotted MHI2_KR_AU57x_S0035 > MHI2_ER_AU57x_K3663

### ISSUE THREAD

**Issue by R3DcooDe** [Mr-MIBonk/M.I.B._More-Incredible-Bash#306]
Hello

Audi A6 2016 Korean with firmware MHI2_KR_AU57x_S0035 /  download mib latest version , copied to brand new fat 32 SD Card .   open red menu started update - engine off, ignition on  after first reboot a Green Screen Doing its magic appears and stuck there forever i waited over 15 minutes  nothing happened.  i proceed with Force reboot,    after unit boot up to normal mode there was no mib installed -  so i repeat step 1 again , and this time mib was Installed  successfully..    i opened mib and proceed with conversation change to EUROPE after mib finished i run EU firmware from red menu -  firmware started updating on Korean Language  until after first reboot unit switched back to English's.. 

Part 2 - Now Unit is with EU Firmware  MHI2_ER_AU57x_K3663

i opened mib and Patch AIO  everything was done successfully  BUT after reboot there is no AUDI SMARTPHONE INTERFACE so no Carplay Andorid Auto.     however maps was installed fine without any problem //   when i go to setup mmi audi smartphone interface is grayed out , gray color 

here are the backup from mib backup folder for investigating

Link: https://we.tl/t-ybphqgrL0K

**Comment by Cupidstunt79** [comment]
Do you have a CarPlay enabled usb port, from what I’ve read not all are CarPlay enabled some and are just for phone charging

**Comment by R3DcooDe** [comment]
> Do you have a CarPlay enabled usb port, from what I’ve read not all are CarPlay enabled some and are just for phone charging

yes mate it has 2 stanart usb ports like on all audi a6 2016 mhi2 - the thing is it does not show at menu, there is no audi smartphone activated :/

**Comment by harman-f** [comment]
seems the finalscript did not run properly on the 1st run.

This can happen....

You did install the 3663 AIO?

**Comment by R3DcooDe** [comment]
> seems the finalscript did not run properly on the 1st run.
> 
> This can happen....
> 
> You did install the 3663 AIO?

nope i didn't install 3663 AIO -   i Installed K3663 and after installed MIB Again and run patch from mib- i always do it in this way

**Comment by je8ker** [comment]
How do install k3663? i don't install k3663

**Comment by blvckbeard1337** [comment]
@R3DcooDe @harman-f  Can you describe me in short term how should i convert my system MHI2_KR_AU57x_S0035 to MHI2_ER_AU57x_K3663,

I normally download the new version but I could'nt update because It says it doesnt support region. If you can just give me an idea how to fix it.

**Comment by hguri** [comment]
hello i am interested to do also this conversation from KR to EU , to my audi a5 with mib2 ... can you help please ?! i have vcp and dlink or can make also without it(vcp i have, but dlink not) ?! thanks

**Comment by je8ker** [comment]
im SW version MHI2_KR_AU57x_S0035 install MIB but activate apple carplay but not activate carplay 
i want try SW update or EU SW install my car how to activate car play
im a6 c7 F/L model SW version MHI2_KR_AU57x_S0035

**Comment by R3DcooDe** [comment]
hello 50 euro paypal - i can help you convert and install
________________________________

**Comment by dielli12** [comment]
Hello R3DcooDe,

I'm having similar issues regarding to the conversion of the MHI2 System from Korea to Europe. 
I will pay you to help me. For more info write to me at: dielli.b.lakna@gmail.com

**Comment by rept1leuser** [comment]
Hi, can u please tell me where to find the update for the firmware update i need the excact one but cant seem to find

**Comment by T3r3A** [comment]
@R3DcooDe Please can you tell how much did the EU firmware take to install ? As i see from other forums it takes 7 hours..
Thanks
