### ISSUE TITLE
Problems train to EU from USA

### ISSUE THREAD

**Issue by Suchar222** [Mr-MIBonk/M.I.B._More-Incredible-Bash#31]
Hello, i have problem train to EU from USA. 
My : MHI2_US_AUG11_S0533
![received_1561954920921831](https://user-images.githubusercontent.com/112582454/187768625-9d39c1b8-a029-4086-8e41-62ba4d87335b.jpeg)

Where is problem?

**Comment by harman-f** [comment]
US FW is too old. binaries missing/not compatable. Update to latest US FW before conversion.

**Comment by Suchar222** [comment]
And what update will work?

**Comment by Suchar222** [comment]
MHI2_US_AU57X_K0539_MU1062 not work....

**Comment by harman-f** [comment]
Yes, S version is not part of the supportedtrains list

```SupportedTrains = "MHI2_US_AUG11_P0526*,MHI2_US_AUG11_P0533*,MHI2_US_AUG11_P0534*,MHI2_US_AU57x_P0536*,MHI2_US_AU57x_K0538*"
```

**Comment by harman-f** [comment]
[metainfo2.txt](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/9530062/metainfo2.txt)

Here you go!

In case you have a BOSE sound system installed, you have to either disbale it in update or remove it from metainfo.
Otherwise, you will need VCP/ODIS to upload new dataset.

**Comment by Suchar222** [comment]
Thank You for metainfo but Your meta not work....
I send to the SD ->MHI2_US_AU57x_K0538_MU0109(photo)
I think problem is with software in my SD. 
I want final software MHI2_ER_AU57x_K3663_1_MU1425_IAO
Can You make my metainfo for this software:MHI2_ER_AU57x_K3663_1_MU1425_IAO
![20220909_164953](https://user-images.githubusercontent.com/112582454/189380829-3f90cf99-b89b-450a-b5e6-9ffa2dcaa4b5.jpg)

**Comment by harman-f** [comment]
Your MMI is already converted to EU as it seem.
MHI2_US_AUG11_S0533 is still on?

**Comment by Suchar222** [comment]
Yes , i think. 
This is my new photo:
![20220911_173810](https://user-images.githubusercontent.com/112582454/189536471-5aa6b626-34dc-45da-b4e1-2b9d8972b890.jpg)
![20220911_173843](https://user-images.githubusercontent.com/112582454/189536472-e56b2074-9cdc-4c2c-8637-5a8e25acd92a.jpg)
![20220911_173854](https://user-images.githubusercontent.com/112582454/189536473-023b7290-38f5-4389-974c-a34752d09e28.jpg)

**Comment by harman-f** [comment]
Based on your screenshot:
![grafik](https://user-images.githubusercontent.com/98130152/189548486-8be13f29-4dae-4f08-a455-994479836b3d.png)
Your MMI is set to EUROPE in coding.
And therfore installation is failing. Did you already try to convert it with some other means than M.I.B.
I did add Europe to supported region list.

Update to latest US FW. And use M.I.B from here to convert to EU.
 

[metainfo2.txt](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/9543533/metainfo2.txt)

**Comment by Suchar222** [comment]
I was just convert only M.I.B

**Comment by Suchar222** [comment]
I did update to MHI2_US_AU57X_K0538. (Done) 
Now I send to SD MHI2_ER_AU57X_K3663_1_MU1425_AIO
I have next problem.
![Uploading 20220912_194738.jpg…]()

**Comment by Suchar222** [comment]
![Uploading 20220912_194738.jpg…]()

**Comment by Suchar222** [comment]
![Uploading 20220912_203448.jpg…]()

**Comment by Suchar222** [comment]
Software update *** Error A variant conflict occurred!  Main unit variant: MHI2_US_AU57x K0538 Version description variant: Train is blocked Update OPEN

**Comment by harman-f** [comment]
You have to convert to EU 1st.

Uploaded image above are not working

**Comment by Suchar222** [comment]
![Uploading 20220912_194738.jpg…]()

**Comment by Suchar222** [comment]
https://ibb.co/Wy19Sr2

**Comment by Suchar222** [comment]
If I have MHI2_US_AU57x K0538 i have problem with VCDS he cant connect module 5F... 
And i dont have green menu....

**Comment by harman-f** [comment]
install M.I.B again to activate GEM
Convert region to EU
Inastall EU FW

**Comment by Suchar222** [comment]
I installed M.I.B and i hold return+button (left down) 
Green menu does not work...
Why?
It happened when i installed it MHI2_US_AU57x_K0538_MU0109

**Comment by Suchar222** [comment]
![306804153_660216975252177_215317247859636349_n](https://user-images.githubusercontent.com/112582454/190443840-3dc83eee-d933-48d7-89ac-093f7f4b381c.jpg)

**Comment by harman-f** [comment]
Sometimes getting into GEM can be a timing issue on pressing the buttons.
Try again, you can also try to install M.I.B again.

**Comment by Suchar222** [comment]
I installed 10 times and nothing. Is there another way?

**Comment by Suchar222** [comment]
Np. VCP?

**Comment by harman-f** [comment]
GEM activation via M.I.B alsways workd ;)

Issue must have some other origin.

**Comment by Suchar222** [comment]
I update to next software , i hope will by better.
Can You make my metainfo for this software MHI2_US_AU57x K0539 ? 
I have qestion? 😃
I can instal M.I.B by D-link ?

**Comment by harman-f** [comment]
Which latest FW do you mean?
MHI2_US_AU57x_K3341_MU1426?

You can run all M.I.B function via putty from shell.

**Comment by Suchar222** [comment]
No. i want MHI2_ER_AU57x_K3341_MU1426
For Europe. 
. 
I cant update to MHI2_ER_AU57x_K3341_MU1426
Why? Because not work M.I.B. 
What i have to did?
I had first time MHI2_US_AUG11_S0533
I have now MHI2_US_AU57x K0538. After update my module 5F not work. (No connect)
Mayby when i will update to MHI2_US_AU57x K0539 i hope "5F" will work.
 This is why i need metainfo for 
MHI2_US_AU57x K0539
I have:
-VCDS
-VCP
-D-link E100

**Comment by justinthegeek** [comment]
> [metainfo2.txt](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/9530084/metainfo2.txt)
> 
> Here you go!
> 
> In case you have a BOSE sound system installed, you have to either disbale it in update or remove it from metainfo. Otherwise, you will need VCP/ODIS to upload new dataset.

How are you generating the metainfo files? I want to skip to k3324_1 but can't seem to find the trains along the way.

**Comment by harman-f** [comment]
No tool, manual editing.
Which FW do you have currently on your unit?

MHI2_US_AU57x_K3324_1_MU0925
SupportedTrains = "MHI2_US_AU57x_P3237*,MHI2_US_AU57x_P3317*,MHI2_US_AU57x_K3324*"

**Comment by justinthegeek** [comment]
I’m currently on MHI2_US_AU57x_K0538

**Comment by justinthegeek** [comment]
I figured out how to modify the file, thank you for the push in the right direction :)

**Comment by willblk973** [comment]
Hello, I have the same train MHI2_US_AUG11_S0533. Is it possible for you to create a meta file for me to go to MHI2_US_AU57x_K3341_MU1426

**Comment by MrGonk** [comment]
> Hello, I have the same train MHI2_US_AUG11_S0533. Is it possible for you to create a meta file for me to go to MHI2_US_AU57x_K3341_MU1426

This is exactly what I need, too. Am I seeing this correctly, that the only alteration you need to make to the metainfo file would basically be to add "MHI2_US_AUG11*," to the "supportedtrains" list, written the same way all the other supported train references are?
