### ISSUE TITLE
Porsche PCM 4.0

### ISSUE THREAD

**Issue by kora0** [Mr-MIBonk/M.I.B._More-Incredible-Bash#315]
I need help ASAP
After uninstalling MIB from Porsche Cayenne PCM 4, the system restarted several times and now the screen is black and cannot be turned on.

**Comment by rbakjaji** [comment]
Did you end up finding a solution?

**Comment by hanbi0011** [comment]
Can I get some help, too?

**Comment by kora0** [comment]
> Can I get some help, too?

just disconnect the quadlock for about 10 minutes and connect again
