### ISSUE TITLE
GEM very small and unreadable

### ISSUE THREAD

**Issue by werdck** [Mr-MIBonk/M.I.B._More-Incredible-Bash#318]
Disclaimer: This might be unrelated to M.I.B.

After installing M.I.B., my GEM screen is very small, like it was zoomed out to ~30% of display size.
Is this a known issue, or at least something that can be changed / fixed?

I have VCP available if necessary.

Log and photo attached.

[MU1326-JTH-07607.12.183409002C.log](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/12420608/MU1326-JTH-07607.12.183409002C.log)

![GEM](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/35466437/b43abf82-8a29-4790-9c54-89ac43817914)
![M.I.B.](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/35466437/e214da80-df9e-40bf-ad86-d746ef4db7da)

**Comment by werdck** [comment]
Resolved.
My MHI2 unit was incorrectly coded (Bytes 01 and 02). After fixing that yesterday, menu is "fullscreen" again.

Closing.

**Comment by h4n1793** [comment]
Hey sorry that this thread has been closed but how did you fix this issue I have updated my firmware and now my screen is the same size as what’s in your picture

**Comment by werdck** [comment]
For me it was stg 5F, bytes 01 and 02 that were misconfigured. Those hold your car's model and engine type for display in the MMI. You should search for coding strings of your vehicle model, module 5F Infotainment.

**Comment by h4n1793** [comment]
What would I need to change them to I have a Audi a3 2017 model with nav plus

**Comment by dabrase7** [comment]
Hi, after installing MIB and updating my Audi A3 MMI, the GEM is small and unreadable as well. I don't really know what stg 5F means. What values are correct for bytes 01 and 02? How do you search and configure that? Is it using VCDS or ODBII? Please, I need to solve this issue to continue maps installation and other features using GEM, thanks

**Comment by h4n1793** [comment]
On the odb11 search the 5f module it’s the multimedia module select long
coding and under bytes 01 and 02 you need to recode it to your vehicle
class and derivate if you know them what car do you have
