### ISSUE TITLE
MHI2Q_ER Installation on on MU Software 1329

### ISSUE THREAD

**Issue by zverko76** [Mr-MIBonk/M.I.B._More-Incredible-Bash#362]
Hi, is it possible to install  on MHI2Q_ER_AUG22_P5152 on MU Software 1329?
I saw on YouTube that someone installed on the MHI2Q_ER system. I tried the same but it didn't work.
It came out on the display to go to diagnostics and do Start version compare. I solved that through obd11 with the B201A calculator.
I rebooted the system but the MIB didn't install. What did I do wrong?
![1700847426322](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/151952977/51270100-453a-4bf9-809a-aa01378157fa)

**Comment by Schmisoo** [comment]
Read the installation instructions of m.i.b. before doing anything

**Comment by zverko76** [comment]
> Read the installation instructions of m.i.b. before doing anything

I did everything as it says in the instructions and it didn't work.
![1700914681265](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/151952977/fcae1b13-4665-4083-b53f-e468e5ed333d)

**Comment by DipeshChunilal** [comment]
i am struggling to find this:MHI2Q_ER_AUG22_P5152 software to download FROM MIBSOLUTION as currently running MHI2Q_ER_AUG22_P5092.
can someone help?

**Comment by koziolk** [comment]
@DipeshChunilal Was MHI2Q_ER_AUG22_P5152 even released? I wasn't able to find this version but I saw some cars had it installed.

**Comment by neoalius** [comment]
following ..

and If some can send me the down load link for MHI2Q_ER_AUG22_P5092. It will be greatly appreciated
