### ISSUE TITLE
Copy folder MHI2_ER_VWG11_S2125_MU0343_Patch to SD card

### ISSUE THREAD

**Issue by rashidisayev** [Mr-MIBonk/M.I.B._More-Incredible-Bash#378]
**Describe the bug**
Apologies for the potentially basic inquiry; I'm relatively inexperienced in car firmware matters. While attempting to patch AOI, I encountered an instruction to "Copy folder MHI2_ER_VWG11_S2125_MU0343_Patch to SD card." Could you please clarify what this folder is and where I can obtain it? Any guidance on the necessary steps would be appreciated.

**Check known issues before reporting**
Make sure you have checked here:
https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/wiki/Prepare-M.I.B-SD-card-&-install-M.I.B#%EF%B8%8F-trouble-shooting-%EF%B8%8F

**Add M.I.B LOG file to your report**
Always attach your M.I.B LOG file!
Check M.I.B SD card in folder `/backup/` and upload that file together with your report.

**Screenshots**
[MU0343-LOG.txt](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/files/13841385/MU0343-LOG.txt)

![IMG_7268](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/31877426/1fd2fe80-556d-490d-9d9f-a1aed7e5b83c)

**Comment by halski** [comment]
Hi @rashidisayev, I am getting the same error when trying to patch mine from MHI2_ER_VWG11_S2125 to MHI2_ER_VWG11_K3342. 
Did you somehow obtain the patch ?
