### ISSUE TITLE
Audi A4 B9 MHI2Q US to EU with success...but problem with frequency FM, when car is start run

### ISSUE THREAD

**Issue by VAGserwis** [Mr-MIBonk/M.I.B._More-Incredible-Bash#425]
Hi all ;)
I do with success conversion MHI2Q from USA to EU, all working property , maps, EU language etc, all good...but problem with frequency FM....I try many times "save" radio program from 1 to 6, and add to my favourite...but, when I turn off car, wait around 10 min, frequency automatic come back to 87,5...and I need manualy select my favourite radio, MIB2Q dont remember the last radio station..maybe someone know where is mistake ? my traint now is mhi2q_er_aug22_p5092
Best Regards

**Comment by Avantgardt** [comment]
Good afternoon, did you solve this problem?

**Comment by traycho** [comment]
Same issue, when I click scan they appear again but only 87.5 on startup.

**Comment by traycho** [comment]
@VAGserwis  I have same issue , is this resolved, it seems I am missing even the scan function, only seek available from the radio.

**Comment by Gruby1983** [comment]
> Cześć wszystkim ;) Udało mi się przekonwertować MHI2Q z USA na UE, wszystko działa, mapy, język UE itd., wszystko ok... ale mam problem z częstotliwością FM... Wielokrotnie próbowałem „zapisać” programy radiowe od 1 do 6 i dodać do ulubionych... ale kiedy wyłączam samochód, czekam około 10 minut, częstotliwość automatycznie wraca do 87,5... i muszę ręcznie wybrać moje ulubione radio, MIB2Q nie pamięta ostatniej stacji radiowej... może ktoś wie gdzie jest błąd? Mój pociąg teraz nazywa się mhi2q_er_aug22_p5092 Pozdrawiam

Hi explain me step by step how to conwert from us to EU please 
![Messenger_creation_197b24b9-eef7-4e5f-8dd7-be489dd3745b](https://github.com/user-attachments/assets/b53507f5-cbb1-43f2-834c-737754314e41)
