### ISSUE TITLE
Problem with mibsolution site

### ISSUE THREAD

**Issue by matim23** [Mr-MIBonk/M.I.B._More-Incredible-Bash#426]
Hi there!
The website has a significant issue. Nothing works despite my repeated attempts using several web engines.
A file called 20230926_MIB_Patches.7z is actually mandatory for me. Is there someone who could share it?

I apologize for any trouble caused, I'm new to this forum.
Thank you in advance. 
Cheers!

**Comment by vut73a** [comment]
email?

**Comment by matim23** [comment]
> email?

kodowaniemateusz@gmail.com

**Comment by vut73a** [comment]
ok

**Comment by matim23** [comment]
Thank you!

**Comment by vut73a** [comment]
https://drive.google.com/file/d/1wTINSKGeTVVMU-a2ODsFqcpUVSB97LQh/view?usp=sharing

**Comment by vut73a** [comment]
?

**Comment by matim23** [comment]
I requested acces

**Comment by vut73a** [comment]
yes, normal?

**Comment by matim23** [comment]
Yes. thank you!

**Comment by vut73a** [comment]
oupen?

**Comment by ludo5962** [comment]
bonjour le fichier est il le dernier en dates si non avais vous un fichier plus récent merci.

**Comment by vut73a** [comment]
У меня его нет, сам ищу, может он у вас есть?

ср, 5 июн. 2024 г., 11:51 ludo5962 ***@***.***>:

**Comment by engineerhasanbor** [comment]
Hello guys, I've checked the website and It was not on right now. I need a patch for MHI2_ER_AUG22_P3346 can someone share it for me ?

**Comment by vut73a** [comment]
> Привет, ребята, я проверил сайт, и сейчас его там нет. Мне нужен патч для MHI2_ER_AUG22_P3346, может кто-нибудь поделиться им для меня?

https://drive.google.com/file/d/1wTINSKGeTVVMU-a2ODsFqcpUVSB97LQh/view?usp=drivesdk

**Comment by richiekaby** [comment]
Hello guys, I've checked and the website was not accessible. Looking for firmware update my vw golf mk7 either MHIG_JP_VW_K0415 or MHIG_JP_VW_K0336

**Comment by domek2222** [comment]
Hello guys, I've checked and the website was not accessible.  Looking for firmware update.  I need a patch for mhi2q er aug22 p5092 mu1329.  I don't have the code 23000ee.

**Comment by Lifeopti** [comment]
Hi guys

Does any have this file and want to share

MSTD_EU_SE_P5310

**Comment by Rami916** [comment]
Hi
I have an ateca 2023 manual my sofware is on 0841 and i don't have a seat connect cause i leave in algeria
Please halp me

**Comment by SlipstreamFPV** [comment]
Any chance of a download link to: MHIG_EU_AU_K1555 @vut73a

**Comment by vut73a** [comment]
20230926_MIB_Patches.7z 
patch for MHI2(Q),  patch for MHI2 ссылка  работает  6 дней,  может кому-то нужно, пользуйтесь : 
https://fex.net/ru/s/akv0tdf

**Comment by ZdenekR123** [comment]
Hey guys does anyone have these following files for updates ?
Or does anyone has like a fuctional google drive where are all the files or at least some ? 
Thanks Yall
MEN2_EU_SKGPX_P8078
MEN2_EU_SKGPX_P8203

**Comment by Rami916** [comment]
Does any one have these file for update
MOI3_EU_SE_R8700L
