### ISSUE TITLE
Help with update version

### ISSUE THREAD

**Issue by matim23** [Mr-MIBonk/M.I.B._More-Incredible-Bash#431]
Hello, 
I would like to perform an EU conversion on my AUDI A4 B9 with MHI2_US_AUG22_P3252 MU software: 0692.
Would it be possible to install the MHI2_ER_AUG22_P3241 MU software: 0678 without bricking the system? I know it's a downgrade, but I can't seem to locate an equal or even newer version.
Thanks in advance

**Comment by vut73a** [comment]
}-     MHI2_US_AUG22_K3347    }-      MHI2_ER_AUG22_P3346

**Comment by matim23** [comment]
Спасибо! :)

**Comment by matim23** [comment]
Спасибо! :)

**Comment by qf512415007** [comment]
谁知道MIB皮肤更换教程嘛？

**Comment by Petrit95** [comment]
Hello i have this please can you halp me i wanna convert from USA-EUROPE MY SOFTWARE IS  (MHI2_US_AUG22_P3252)(MU0692)

![image](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/122656334/b76e1c29-d600-4727-b5b3-2d5139c00c20)

**Comment by vut73a** [comment]
> Hello i have this please can you halp me i wanna convert from USA-EUROPE MY SOFTWARE IS (MHI2_US_AUG22_P3252)(MU0692)
> 
> ![image](https://private-user-images.githubusercontent.com/122656334/340783335-b76e1c29-d600-4727-b5b3-2d5139c00c20.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NDE1MDAsIm5iZiI6MTcxODc0MTIwMCwicGF0aCI6Ii8xMjI2NTYzMzQvMzQwNzgzMzM1LWI3NmUxYzI5LWQ2MDAtNDcyNy1iNWIzLTJkNTEzOWMwMGMyMC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMjAwNjQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGE5ZDJmZjlhOWRjZTZlNzQ5MDJiNjU5ZWQ5NDZkOTQ1NTA4OGI0ZWVkZWI3NzU5NmExNzliNzAyZTFlODRhYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0Lrsjs1-a9ANSK_9q1Svxyga6jv_m11m1o3Edrcs8pA)

MHI2_ER_AUG22_P3346 ваша последняя прошивка для Европы!
 Вы должны скачать её с mibsolution.one

**Comment by vut73a** [comment]
> Hello i have this please can you halp me i wanna convert from USA-EUROPE MY SOFTWARE IS (MHI2_US_AUG22_P3252)(MU0692)
> 
> ![image](https://private-user-images.githubusercontent.com/122656334/340783335-b76e1c29-d600-4727-b5b3-2d5139c00c20.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NDE5NDcsIm5iZiI6MTcxODc0MTY0NywicGF0aCI6Ii8xMjI2NTYzMzQvMzQwNzgzMzM1LWI3NmUxYzI5LWQ2MDAtNDcyNy1iNWIzLTJkNTEzOWMwMGMyMC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMjAxNDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTRhMzhhYjBkZGYyZmYxMDFlN2RhY2VhM2EyNzgzOWU5NjZjMmIzOTk0ZWRiMjNiODY4YTllNDYwODEwZjE5NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FP8hsCfvo5R1e-PsXITZZARM-Ur2ZQM4moHD3mjGkRY)
![IMG_20240618_231337_241](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/163304103/bc03ac94-76b5-4ba5-b270-3b310f6d1c64)

**Comment by Petrit95** [comment]
Also i have bose system do i need to update afer that 

Кроме того, у меня есть система bose, нужно ли мне обновить ее?

**Comment by Petrit95** [comment]
![image](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/122656334/7538d4dd-58b2-47b1-9614-fb48d2588b70)

**Comment by Petrit95** [comment]
I donweload the same MHI2_ER_AUG22_P3346 
 But this is the typeof message

**Comment by vut73a** [comment]
Bose обновлять было не нужно, после обновления прошивки с Bose  получается конфликт

**Comment by Petrit95** [comment]
Возможно, другая прошивка в Европу для обновления прошивки

**Comment by vut73a** [comment]
Последняя для Америки 3347, для Европы будет 3346 -100%
Вам нужно было обновить сначала до последней Америки 3347, а потом конвертировать в Европу 3346

**Comment by vut73a** [comment]
> Возможно, другая прошивка в Европу для обновления прошивки

Последняя для Америки 3347, для Европы будет 3346 -100%
Вам нужно было обновить сначала до последней Америки 3347, а потом конвертировать в Европу 3346 .
Я надеюсь вы так делали?

**Comment by vut73a** [comment]
> Возможно, другая прошивка в Европу для обновления прошивки

Последняя для Америки 3347, для Европы будет 3346 -100%
Вам нужно было обновить сначала до последней Америки 3347, а потом конвертировать в Европу 3346 .
Я надеюсь вы так делали?

**Comment by vut73a** [comment]
> Возможно, другая прошивка в Европу для обновления прошивки

Последняя для Америки 3347, для Европы будет 3346 -100%
Вам нужно было обновить сначала до последней Америки 3347, а потом конвертировать в Европу 3346 .
Я надеюсь вы так делали?

**Comment by Petrit95** [comment]
Я успешно обновил прошивку до Европы, но теперь у меня есть проблема с картами, не могли бы вы немного подтолить меня, я исправляю программное обеспечение и все, кроме сообщения о конфликте навигации

**Comment by vut73a** [comment]
У вас есть Whatsapp?

**Comment by vut73a** [comment]
> Я успешно обновил прошивку до Европы, но теперь у меня есть проблема с картами, не могли бы вы немного подтолить меня, я исправляю программное обеспечение и все, кроме сообщения о конфликте навигации

У вас есть Whatsapp или viber?

**Comment by Petrit95** [comment]
Да, у меня есть whatsaap

0038971307060 напишите мне, пожалуйста

**Comment by Petrit95** [comment]
привет по вашей ссылке на карту, которую вы мне прислали, я загружаю и помещаю ее на SD-карту (P350), после этого я ставлю и начинаю обновляться, но все равно (Error communicating with device Speech_Check), возможно, карта неправильно установлена ​​на SD

![image](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/122656334/56677dce-d08d-42c0-8b74-6d93678a0c8d)

![image](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/122656334/6026425b-66c3-45b5-80b7-542a6dc930eb)

![image](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/122656334/58925111-b1aa-4725-806e-477e0a6a8998)

![image](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/122656334/a16d57f6-2475-464a-818a-aae1aad46206)

![image](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/122656334/4c035059-b32e-404e-8824-f22ce3e28b4b)

![image](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/122656334/0a52f14f-7ff7-47fe-8095-d7b12288bb4c)

**Comment by deepalarm** [comment]
MMHI2_ER_AUG22_P3241_MU0678  patche neded

**Comment by dimamelnyk2805-blip** [comment]
Привіт всім 
Хотів запитати хто встановлював прошивку 
MHI2_ER_AUG22_P3346
Перед встановлення чи потрібно щось змінювати в налаштуванні

**Comment by vut73a** [comment]
> Привіт всім Хотів запитати хто встановлював прошивку MHI2_ER_AUG22_P3346 Перед встановлення чи потрібно щось змінювати в налаштуванні

Яка прошивка  у вас щас є по факту,  яке авто, для початку?
