### ISSUE TITLE
MHI2_US_POG11_K3300 0809

### ISSUE THREAD

**Issue by pavitardua** [Mr-MIBonk/M.I.B._More-Incredible-Bash#498]
When I tried following the steps I see the following screens in the order I am pasting them. I had to click on Cancel backup documentation and come out of the setup as it did not go through. 

**Screenshots**
![WhatsApp Image 2024-06-25 at 06 43 08](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/6836799/e2311e77-f832-4abf-b1e7-f9b4fe533607)
![WhatsApp Image 2024-06-25 at 06 43 09](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/6836799/31119ce0-7ce9-414e-b9ab-06837ffeff29)
![WhatsApp Image 2024-06-25 at 06 43 10](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/6836799/2e2971f5-2527-4277-ad89-1bda8f2fb1a2)
![WhatsApp Image 2024-06-25 at 06 43 10 (1)](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/6836799/3df8a87e-88ba-4ae0-846b-884a5deb2cdf)
![WhatsApp Image 2024-06-25 at 06 43 11](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/6836799/0af21399-c4bf-4432-8ba8-341aa2f31312)
![WhatsApp Image 2024-06-25 at 06 43 11 (1)](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/6836799/3f7fc596-84a6-457c-a6f7-ca57ef67f361)
![WhatsApp Image 2024-06-25 at 06 43 12](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/6836799/bd8b6737-8651-4d8d-b33b-9398ca521d6c)
![WhatsApp Image 2024-06-25 at 06 44 18](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/6836799/4e5c9916-85c8-4dfa-9097-8f8f2a1359db)
![WhatsApp Image 2024-06-25 at 06 44 19](https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/6836799/5316af50-4a62-4cf2-93e0-10bfa18ba3e5)

P.S I saw much later that my firmware version **MHI2_US_POG11_K3300 0809** was not listed in the Patch Compatibility Table. Does this mean it won't work for this version ever? Can I expect an update that supports this particular version?

**Add M.I.B LOG file to your report**
I don't see any logs in /backup/logs folder.

**Additional context**
Add any other context about the problem here. - Luckily I am able to still use the stock PCM of my Porsche and nothing has broken. Tested connecting an iphone after this, it says Ipod Connected so it confirms Car Play was not installed.
Was the unit worked on before? - Nope
Is the unit stock in car or a retrofit? - It's a stock unit

There is another PDF in this folder named "2022_06_MHI2_Password_List_V4.0.pdf" which has the firmware version I have on my car, I don't know whether this means that it was supposed to be compatible. Also if someone could explain whether we ever need to use this hash and password from the PDF.
<img width="781" alt="Screenshot 2024-06-25 at 6 56 06 AM" src="https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/assets/6836799/e4eebbbc-44dd-44eb-a6b4-c8fa0bf63027">

**Comment by Apps215** [comment]
pavitardua did you ever get any resolution to this?

**Comment by pavitardua** [comment]
Yes, I have used this repository and it's instructions https://github.com/harman-f/MHI2_US_POG11_K5186_1-MU1476-AIO which is compatibe with my firmware.

Also this video is helpful: https://youtu.be/QPRqR47_9qo?si=7SeiboEDCn55KaTA

Please follow this thread: https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/issues/374#issuecomment-2227302515

Note: Please ensure you are using a good SD card, I haven't use external power but have kept the car engine turned on for the entire length of the updates which was about 40 minutes. Let me know if you have more questions as I have recently done this.

**Comment by pavitardua** [comment]
Yes, I have used this repository and it's instructions https://github.com/harman-f/MHI2_US_POG11_K5186_1-MU1476-AIO which is compatibe with my firmware.

Also this video is helpful: https://youtu.be/QPRqR47_9qo?si=7SeiboEDCn55KaTA

Please follow this thread: https://github.com/Mr-MIBonk/M.I.B._More-Incredible-Bash/issues/374#issuecomment-2227302515

Note: Please ensure you are using a good SD card, I haven't use external power but have kept the car engine turned on for the entire length of the updates which was about 40 minutes. Let me know if you have more questions as I have recently done this.

**Comment by rd007000** [comment]
Hello pavitardua

The pictures above show you have a Macan like I do. The video you posted is for a Boxster.  Did you follow the same procedure for your Macan as in the video?

Thanks
