### ISSUE TITLE
No Patch for MHI2_ER_POG11_P5250 MU Software 1502

### ISSUE THREAD

**Issue by HansiNEA** [Mr-MIBonk/M.I.B._More-Incredible-Bash#512]
I have an new Porsche Cayman, build 03/24, trying to update with 3.6 and 3.71 is not possible. Error: The signature of metainfo2.txt is not correct. Also there is no directory with MHI2_ER_POG11_P5250 in the patches directory.

Help

**Comment by HansiNEA** [comment]
Hello, could someone help me? Who develop new Patches? Should I Upload Something? Ist The Project dead?

**Comment by HansiNEA** [comment]
Problem solved

**Comment by HansiNEA** [comment]
Closed

**Comment by lukaspour** [comment]
@HansiNEA  how did you solve this, please? I have exactly the same problem. Thank you .

**Comment by darkmrscod** [comment]
Hello

I have the solution. Activation only via SD, no dlink needed. Already did on Rs Spyder 2024
not free
