### ISSUE TITLE
Feature Request: Audi MIB2 Dual Navigation Patch

### ISSUE THREAD

**Issue by rasorjb** [Mr-MIBonk/M.I.B._More-Incredible-Bash#8]
Would it be too much trouble to develop the Dual Navigation (Car Play and Built-in) patch for MIB2 for Audi?

**Comment by harman-f** [comment]
The Java patch required to enable this is very FW specific. 

Either we find a more common place in java code to patch it or mutliple patches are required for a narrow range of FWs and brands.

Origin of this patch is here: https://github.com/jilleb/mib2-toolbox/pull/189
