### ISSUE TITLE
Support for MHS firmware?

### ISSUE THREAD

**Issue by alexisbronchart** [Mr-MIBonk/M.I.B._More-Incredible-Bash#92]
Would this work for firmware ˋMHS2_ER_AU_P2035ˋ ? (Audi A3 2019) I checked compatibility list and since all versions start with MHI2 I doubt it would work but still checking 😊

**Comment by suplstfdo** [comment]
Hi @alexisbronchart ,
could you get it to work? I have the same firmware and wondering the same thing.
